<PageHeading />

<TabBar {tabs} bind:activeTab/>

{#if activeTab == "Edit"}
    {#if mode === "profile"}
        <EditProfile 
            {initialItem}
            bind:validationErrors
            bind:item
            bind:this={editProfile}
        />
    {:else} <!-- mode === "post" -->
        <EditPost
            bind:validationErrors
            bind:warnings
            bind:item
            bind:files={fileAttachments}
            bind:this={editPost}
        />
    {/if}
{:else}
    <!-- Preview: -->
    <ItemView
        userID={userID.toString()}
        signature=""
        {item}
        linkMode="newWindow"
        previewMode
        previewFiles={fileAttachments}
    />
{/if}

<!-- force transition:slide|local to be local -->
{#if true}
<div class="item">
    <div class="body">
        <SignAndSend
            {item}
            attachments={fileAttachments}
            onSendSuccess={clear}
            errors={validationErrors}
            warnings={warnings}
        />    
    </div>
</div>
{/if}


<script lang="ts">
import type { Writable } from "svelte/store"
import { Item } from "../protos/feoblog"


import type { UserID as ClientUserID, UserID } from "../ts/client"
import type { AppState } from '../ts/app';
import ItemView from './ItemView.svelte'
import EditProfile from './EditProfile.svelte';
import EditPost from './EditPost.svelte';
import SignAndSend from "./SignAndSend.svelte";
import { ConsoleLogger, FileInfo } from "../ts/common";
import { getContext } from "svelte";
import PageHeading from "./PageHeading.svelte";
import TabBar from "./TabBar.svelte";

let logger = new ConsoleLogger({prefix: "<EditorWithPreview>"})
logger.debug("loaded")
let appState: Writable<AppState> = getContext("appStateStore")

// What kind of thing are we editing?
// I imagine I'll want to make a "reply" type here too.
// There will probably be a separate, inline editor for "comment" types since they'll be simpler.
export let mode: "post"|"profile" = "post"

let tabs = ["Edit", "Preview"]
let activeTab = "Edit"

// Can provide an initial item for editing.
export let initialItem: Item|undefined = undefined

let fileAttachments: FileInfo[] = []

let userID: ClientUserID
$: userID = $appState.requireLoggedInUser()


// Validation Errors from EditProfile/EditPost:
let validationErrors: string[] = []
let warnings: string[] = []


// The Item protobuf generated by EditProfile/EditPost.
let item: Item = new Item()

let editPost: EditPost|undefined = undefined
let editProfile: EditProfile|undefined = undefined

function clear() {
    logger.debug("clear()")
    editPost?.clear()
    // TODO: editProfile?.clear()
}

</script>

