<PageHeading {breadcrumbs} />

<div class="dualPaneEditor">
    {#if mode === "profile"}
        <EditProfile 
            {initialItem}
            bind:validationErrors
            bind:item
            bind:this={editProfile}
        />
    {:else} <!-- mode === "post" -->
        <EditPost
            bind:validationErrors
            bind:warnings
            bind:item
            bind:files={fileAttachments}
            bind:this={editPost}
        />
    {/if}
    
    <!-- Preview: -->
    <ItemView
        userID={userID.toString()}
        signature="unknown"
        {item}
        linkMode="newWindow"
        previewMode
        previewFiles={fileAttachments}
    />

    <!-- force transition:slide|local to be local -->
    {#if true}
    <div class="item">
        <div class="body">
            <SignAndSend
                {item}
                attachments={fileAttachments}
                onSendSuccess={clear}
                errors={validationErrors}
                warnings={warnings}
            />    
        </div>
    </div>
    {/if}

</div>

<style>

@media (min-width: 70em) {
    .dualPaneEditor {
        display: inline-grid;
        width: 100%;
        /* an .item has max-width 55em. +1em grid gap */
        max-width: 111em;
        grid-template-columns: 1fr 1fr;
        grid-gap: 1em;
        padding: 1em;
        padding-top: 0;
    }
    .dualPaneEditor > :global(*) {
        margin: 0px;
    }
}
</style>

<script lang="ts">
import type { Writable } from "svelte/store"
import { Item } from "../protos/feoblog"


import type { UserID as ClientUserID, UserID } from "../ts/client"
import type { AppState } from '../ts/app';
import ItemView from './ItemView.svelte'
import EditProfile from './EditProfile.svelte';
import EditPost from './EditPost.svelte';
import SignAndSend from "./SignAndSend.svelte";
import type { FileInfo } from "../ts/common";
import { getContext } from "svelte";
import PageHeading from "./PageHeading.svelte";

let appState: Writable<AppState> = getContext("appStateStore")

// What kind of thing are we editing?
// I imagine I'll want to make a "reply" type here too.
// There will probably be a separate, inline editor for "comment" types since they'll be simpler.
export let mode: "post"|"profile" = "post"

// Can provide an initial item for editing.
export let initialItem: Item|undefined = undefined

let fileAttachments: FileInfo[] = []

let userID: ClientUserID
$: userID = $appState.requireLoggedInUser()
$: breadcrumbs = getBreadcrumbs(userID)

function getBreadcrumbs(userID: UserID|null) {

    let crumbs = []

    if (userID) {
        crumbs.push({userID})
    }

    if (mode == "post") {
        crumbs.push({text: "New Post"})
    } else if (mode == "profile") {
        crumbs.push({text: "Edit Profile"})
    }
    
    return {crumbs}
}


// Validation Errors from EditProfile/EditPost:
let validationErrors: string[] = []
let warnings: string[] = []


// The Item protobuf generated by EditProfile/EditPost.
let item: Item = new Item()

let editPost: EditPost|undefined = undefined
let editProfile: EditProfile|undefined = undefined

function clear() {
    editPost?.clear()
    // TODO: editProfile?.clear()
}

</script>

