<div class="dualPaneEditor">
    {#if mode === "profile"}
        <EditProfile 
            {appState} 
            {initialItem}
            bind:validationErrors
            bind:item
        />
    {:else} <!-- mode === "post" -->
        <EditPost
            bind:validationErrors
            bind:item
        />
    {/if}
    
    <!-- Preview: -->
    <ItemView
        {appState}
        userID={userID.toString()}
        signature="unknown"
        {item}
        linkMode="newWindow"
        previewMode
    />

    <!-- force transition:slide|local to be local -->
    {#if true}
    <div class="item">
        <div class="body">
            <SignAndSend
                {appState}
                {item}
            />    
        </div>
    </div>
    {/if}

</div>


<script lang="ts">
import type { Writable } from "svelte/store"
import { Item } from "../protos/feoblog"


import type { UserID as ClientUserID } from "../ts/client"
import type { AppState } from '../ts/app';
import ItemView from './ItemView.svelte'
import EditProfile from './EditProfile.svelte';
import EditPost from './EditPost.svelte';
import SignAndSend from "./SignAndSend.svelte";

export let appState: Writable<AppState>

// What kind of thing are we editing?
// I imagine I'll want to make a "reply" type here too.
// There will probably be a separate, inline editor for "comment" types since they'll be simpler.
export let mode: "post"|"profile" = "post"

// Can provide an initial item for editing.
export let initialItem: Item|undefined = undefined

// May be provided externally if we were provided an item
// TODO: TBH, the fact that this works w/ an initialItem: Item above is just an
// artifact of our serializer having a deterministic output. That may not be the case
// and we may want to pass itemBytes here if we want to verify the signature of profiles
// we load.  Though, maybe that's just not worth it.
export let signature = ""


let userID: ClientUserID
$: userID = $appState.requireLoggedInUser()

// Validation Errors from EditProfile/EditPost:
let validationErrors: string[] = []
// The Item protobuf generated by EditProfile/EditPost.
let item: Item = new Item()



</script>

