[package]
name = "leptos_app"
version = "0.1.0"
edition = "2021"


[dependencies]
leptos.workspace = true
leptos_router.workspace = true

# For WASM builds:
[lib]
crate-type = [
    "cdylib",
    "rlib"
]
