name: Build

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - macos-latest
        # Windows builds are broken, waiting on https://github.com/NfNitLoop/feoblog/issues/16
        # - windows-latest
      # Don't fail fast, if we have a failure on a specific matrix type
      # we want to know which ones:
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3
      with: 
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install NPM dependencies
      working-directory: ./web-client
      run: npm install

    - name: Build JavaScript Client
      working-directory: ./web-client
      run: npm run build
    
    - name: Run Rust Tests
      run: cargo test

    - name: Build Rust
      run: cargo build --release

    - name: Save result
      uses: actions/upload-artifact@v2
      with:
        name: "FeoBlog-${{ matrix.os }}"
        path: |
          ./target/release/feoblog
          ./target/release/feoblog.exe

  show_paths:
    name: Show paths
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      id: download
      uses: actions/download-artifact@v2
    - name: list artifacts
      run: |
        echo pwd:
        pwd

        echo download path: ${{ steps.download.outputs.download-path }}
        dir -R ${{ steps.download.outputs.download-path }}

      